default['application']['user'] = 'zigzag'
default['application']['group'] = 'zigzag'
default['application']['work_dir'] = '/zigzag'
default['application']['db_backup_dir'] = File.join(default['application']['work_dir'], 'db_backup')
default['application']['config_dir'] = File.join(default['application']['work_dir'], 'config')
default['application']['photos_dir'] = File.join(default['application']['work_dir'], 'photos')
default['application']['original_photos_dir'] = File.join(default['application']['photos_dir'], 'original')
default['application']['processed_photos_dir'] = File.join(default['application']['photos_dir'], 'processed')

default['application']['api_serving']['name'] = 'zigzag_api_serving'
default['application']['api_serving']['user'] = 'zigzag_api_serving'
default['application']['api_serving']['work_dir'] = File.join(default['application']['work_dir'], 'api_serving')
default['application']['api_serving']['virtual_env'] = File.join(default['application']['api_serving']['work_dir'], 'virtual_env')
default['application']['api_serving']['config'] = File.join(default['application']['config_dir'], 'api_serving.lighttpd')
default['application']['api_serving']['port'] = 9000
default['application']['api_serving']['daemon']['script'] = '/etc/init.d/zigzag_api_serving'
default['application']['api_serving']['daemon']['pid_file'] = File.join(default['application']['api_serving']['work_dir'], 'daemon.pid')
default['application']['api_serving']['daemon']['error_log'] = File.join(default['application']['api_serving']['work_dir'], 'daemon.error.log')
default['application']['api_serving']['daemon']['debug_log'] = File.join(default['application']['api_serving']['work_dir'], 'daemon.debug.log')
default['application']['api_serving']['lighttpd']['pid_file'] = File.join(default['application']['api_serving']['work_dir'], 'lighttpd.pid')
default['application']['api_serving']['lighttpd']['error_log'] = File.join(default['application']['api_serving']['work_dir'], 'lighttpd.error.log')
default['application']['api_serving']['lighttpd']['access_log'] = File.join(default['application']['api_serving']['work_dir'], 'lighttpd.access.log')
default['application']['api_serving']['django']['fastcgi_host'] = '127.0.0.1'
default['application']['api_serving']['django']['fastcgi_port'] = 9002

default['application']['res_serving']['name'] = 'zigzag_res_serving'
default['application']['res_serving']['config'] = File.join(default['application']['config_dir'], 'res_serving.lighttpd')
default['application']['res_serving']['daemon']['script'] = '/etc/init.d/zigzag_res_serving'
default['application']['res_serving']['daemon']['pid_file'] = File.join(default['application']['work_dir'], 'res_serving.daemon.pid')
default['application']['res_serving']['daemon']['error_log'] = File.join(default['application']['work_dir'], 'res_serving.daemon.error.log')
default['application']['res_serving']['daemon']['debug_log'] = File.join(default['application']['work_dir'], 'res_serving.daemon.debug.log')
default['application']['res_serving']['user'] = 'zigzag_res_serving'
default['application']['res_serving']['port'] = 9001
default['application']['res_serving']['lighttpd']['pid_file'] = File.join(default['application']['work_dir'], 'res_serving.lighttpd.pid')
default['application']['res_serving']['lighttpd']['error_log'] = File.join(default['application']['work_dir'], 'res_serving.lighttpd.error.log')
default['application']['res_serving']['lighttpd']['access_log'] = File.join(default['application']['work_dir'], 'res_serving.lighttpd.access.log')
default['application']['res_serving']['allowed_extension'] = 'jpg|mp4'
default['application']['res_serving']['expire'] = 'access plus 1 months'
