name             'application'
maintainer       'ZigZag'
maintainer_email 'horia141@gmail.com'
license          'All rights reserved'
description      'Installs/Configures the ZigZag application'
long_description ''
version          '0.1.0'

depends 'apt', '~> 2.7.0'
depends 'firewall', '~> 1.1.0'
